package main

import (
	"html/template"
	"net/url"
)

var adminTemplate = template.Must(template.New("admin").Funcs(template.FuncMap{"urlquery": url.QueryEscape}).Parse(`<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ファイル転送</title>
<style>
:root{--text:#202124;--sub:#6b7280;--line:#e5e7eb;--blue:#2563eb;--red:#b42318;--warn:#92400e;--warnbg:#fff7ed}*{box-sizing:border-box}body{margin:0;background:#fff;color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Yu Gothic UI",sans-serif}.wrap{max-width:980px;margin:0 auto;padding:54px 28px 80px}h1{font-size:34px;margin:0 0 8px;letter-spacing:-.02em}h2{font-size:22px;margin:0 0 8px}h3{font-size:17px;margin:0 0 6px}.lead,.muted{color:var(--sub);line-height:1.65}.lead{font-size:16px}.notice{margin:24px 0 0;padding:12px 14px;background:#fafafa;border-left:3px solid #d1d5db}.section{padding:34px 0;border-top:1px solid var(--line)}.section:first-of-type{margin-top:32px}.step{font-size:13px;font-weight:700;color:var(--sub);margin-bottom:8px}.connect{display:grid;grid-template-columns:1fr 1fr;gap:36px}.box{min-width:0}.qr{width:230px;height:230px;border:1px solid var(--line);padding:8px;background:#fff;margin:14px 0}.kv{display:grid;grid-template-columns:110px 1fr;gap:7px 16px;max-width:430px}.value{font-weight:650;overflow-wrap:anywhere}.code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.actions{display:flex;flex-wrap:wrap;gap:10px;margin:18px 0}.btn,.fileLabel{border:1px solid var(--line);background:#fff;color:var(--text);border-radius:6px;padding:10px 14px;font-size:14px;font-weight:650;cursor:pointer}.primary{background:var(--blue);border-color:var(--blue);color:#fff}.danger{color:var(--red)}.fileLabel input{display:none}.grid{display:grid;grid-template-columns:1fr 1fr;gap:28px}.list{margin-top:10px}.file{display:flex;gap:12px;padding:10px 0;border-bottom:1px solid var(--line)}.file span:first-child{flex:1;overflow-wrap:anywhere}.status{margin-top:10px;color:var(--sub);font-size:14px}.ok{color:#166534}.warning{display:none;margin:18px 0;padding:12px 14px;background:var(--warnbg);color:var(--warn);border-radius:6px}.details{margin-top:16px}.details summary{cursor:pointer;color:var(--sub)}.url{overflow-wrap:anywhere;font-size:13px}.end{display:flex;justify-content:space-between;align-items:center;gap:20px}.test{font-size:13px;background:#f3f4f6;padding:6px 9px;border-radius:5px;display:inline-block;margin-top:10px}@media(max-width:760px){.connect,.grid{grid-template-columns:1fr}.wrap{padding:34px 18px 60px}.qr{width:210px;height:210px}.end{align-items:flex-start;flex-direction:column}}
</style></head><body><main class="wrap">
<h1>ファイル転送</h1><div class="lead">{{.DeviceName}} とスマートフォンの間でファイルを送受信します。</div>{{if .TestMode}}<div class="test">VMテストモード — このPC内だけで動作しています</div>{{end}}
<div class="notice">ファイル転送が終わるまでこの画面を閉じないでください。しばらく操作がない場合は自動で終了します。</div>
<div id="timeoutWarning" class="warning"></div>
<section class="section"><div class="connect">
<div class="box"><div class="step">1 / 3</div><h2>Wi‑Fiに接続</h2><div class="muted">スマートフォンのカメラでQRコードを読み取ります。</div>{{if .WiFiQR}}<img class="qr" src="/qr.svg?text={{urlquery .WiFiQR}}" alt="Wi-Fi接続用QRコード">{{end}}<div class="kv"><div class="muted">Wi‑Fi名</div><div class="value">{{.WiFiSSID}}</div><div class="muted">パスワード</div><div class="value code">{{.WiFiPassword}}</div></div>{{if not .TestMode}}<div class="muted" style="margin-top:10px">「インターネットなし」と表示されても正常です。</div>{{end}}</div>
<div class="box"><div class="step">2 / 3</div><h2>転送ページを開く</h2><div class="muted">Wi‑Fi接続後、こちらのQRコードを読み取ります。</div>{{range $i,$u:=.URLs}}{{if eq $i 0}}<img class="qr" src="/qr.svg?text={{urlquery $u.URL}}" alt="転送ページQRコード"><div class="url">{{$u.URL}}</div>{{end}}{{else}}<div class="muted" style="margin-top:18px">転送用ネットワークを確認できませんでした。</div>{{end}}</div>
</div><details class="details"><summary>接続できないとき</summary><div class="muted" style="margin-top:10px">Wi‑Fiがオン、モバイル ホットスポットがオフであることを確認して起動し直してください。</div></details></section>
<section class="section"><div class="step">3 / 3</div><h2>ファイルを送受信</h2><div class="muted">スマホから送る場合はスマホ画面を操作します。PCから渡す場合は下から選びます。</div><div class="actions"><label class="fileLabel primary">スマホに渡すファイルを選ぶ<input id="sharePick" type="file" multiple></label><button class="btn" onclick="openFolder('send')">共有ファイルを開く</button><button class="btn" onclick="openFolder('receive')">受信ファイルを開く</button></div><div id="shareStatus" class="status"></div>
<div class="grid"><div><h3>スマホに渡すファイル</h3><div id="sendList" class="list"></div><button class="btn danger" onclick="clearSide('send')">共有をすべて解除</button></div><div><h3>スマホから受け取ったファイル</h3><div id="recvList" class="list"></div><button class="btn danger" onclick="clearSide('receive')">受信ファイルをすべて削除</button></div></div></section>
<section class="section end"><div><h2>終了</h2><div class="muted">終了すると転送用Wi‑Fiと今回のURLは使えなくなります。</div></div><button class="btn danger" onclick="stopApp()">ファイル転送を終了</button></section>
</main><script>
const admin='/admin/{{.AdminToken}}';let failures=0;
function fmt(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';if(n<1073741824)return(n/1048576).toFixed(1)+' MB';return(n/1073741824).toFixed(2)+' GB'}
document.getElementById('sharePick').addEventListener('change',async e=>{const st=document.getElementById('shareStatus');for(const f of e.target.files){st.textContent='準備中: '+f.name;await upload(f)}st.textContent='スマホに渡すファイルを用意しました。';st.className='status ok';e.target.value='';loadStatus()});
function upload(f){return new Promise(res=>{const x=new XMLHttpRequest();x.open('POST',admin+'/upload?name='+encodeURIComponent(f.name));x.onload=()=>{if(x.status>=200&&x.status<300)res();else{document.getElementById('shareStatus').textContent=x.responseText;res()}};x.onerror=()=>res();x.send(f)})}
async function openFolder(which){await fetch(admin+'/open?which='+which,{method:'POST'})}
async function clearSide(which){if(!confirm(which==='send'?'共有ファイルをすべて解除しますか？':'受信ファイルをすべて削除しますか？'))return;await fetch(admin+'/clear-'+which,{method:'POST'});loadStatus()}
function render(id,fs,empty){const el=document.getElementById(id);if(!fs.length){el.innerHTML='<div class="muted" style="padding:10px 0">'+empty+'</div>';return}el.innerHTML='';for(const f of fs){const d=document.createElement('div');d.className='file';const n=document.createElement('span');n.textContent=f.name;const z=document.createElement('span');z.className='muted';z.textContent=fmt(f.size);d.append(n,z);el.appendChild(d)}}
function warnTimeout(s){const w=document.getElementById('timeoutWarning');const remain=Math.min(Number(s.idleRemainingSec||0),Number(s.absoluteRemainingSec||0));if(remain>0&&remain<=600){const m=Math.max(1,Math.ceil(remain/60));w.textContent='まもなく自動終了します。必要な操作がある場合は続けてください（約'+m+'分）。';w.style.display='block'}else{w.style.display='none'}}
async function loadStatus(){try{const r=await fetch(admin+'/api/status',{cache:'no-store'});if(!r.ok)throw 0;const s=await r.json();failures=0;render('sendList',s.send,'共有中のファイルはありません');render('recvList',s.receive,'まだファイルを受け取っていません');warnTimeout(s)}catch(e){failures++;if(failures>=3)document.getElementById('timeoutWarning').innerHTML='セッションが終了した可能性があります。もう一度利用する場合は Local Phone Transfer を起動してください。';document.getElementById('timeoutWarning').style.display='block'}}
async function stopApp(){if(!confirm('ファイル転送を終了しますか？'))return;await fetch(admin+'/stop',{method:'POST'});document.body.innerHTML='<main class="wrap"><h1>終了しました</h1><p class="lead">この画面は閉じても大丈夫です。</p></main>'}
loadStatus();setInterval(loadStatus,5000);
</script></body></html>`))
