package main

import (
	"html/template"
	"net/url"
)

var adminTemplate = template.Must(template.New("admin").Funcs(template.FuncMap{"urlquery": url.QueryEscape}).Parse(`<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ファイル転送</title>
<style>
:root{--bg:#fff;--text:#222;--sub:#6b6b6b;--line:#e9e9e7;--soft:#f7f7f5;--danger:#b42318;--warn:#8a6500}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:"Segoe UI","Yu Gothic UI",sans-serif}.wrap{max-width:980px;margin:0 auto;padding:42px 28px 72px}.top{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;padding-bottom:28px;border-bottom:1px solid var(--line)}h1{font-size:34px;letter-spacing:-.03em;margin:0 0 8px}.lead{color:var(--sub);font-size:15px;line-height:1.7;margin:0}.badge{font-size:12px;font-weight:700;background:var(--soft);padding:6px 9px;border-radius:6px;color:#555}.notice{margin-top:18px;padding:12px 14px;background:var(--soft);border-radius:8px;color:#555;font-size:14px}.idleWarn{display:none;margin-top:14px;padding:11px 13px;border:1px solid #e6d48d;background:#fffdf2;color:var(--warn);border-radius:7px;font-size:14px}.section{padding:30px 0;border-bottom:1px solid var(--line)}.sectionHead{display:flex;gap:13px;align-items:flex-start;margin-bottom:18px}.num{font-size:13px;font-weight:700;color:#8a8a8a;padding-top:5px}.section h2{font-size:22px;margin:0 0 5px}.section p{margin:0;color:var(--sub);font-size:14px;line-height:1.7}.grid{display:grid;grid-template-columns:1fr 1fr;gap:28px}.qr{width:220px;height:220px;border:1px solid #ddd;padding:8px;background:#fff}.label{font-size:12px;color:var(--sub);margin-bottom:4px}.value{font-size:18px;font-weight:650;overflow-wrap:anywhere}.mono{font-family:Consolas,"SFMono-Regular",monospace}.details{margin-top:12px}.details summary{cursor:pointer;color:#555;font-size:14px}.url{font-size:13px;overflow-wrap:anywhere;color:#555;margin-top:6px}.actions{display:flex;flex-wrap:wrap;gap:9px}.btn,.fileLabel{display:inline-flex;align-items:center;justify-content:center;border:1px solid #d7d7d7;background:#fff;color:#222;border-radius:7px;padding:10px 14px;font-size:14px;font-weight:650;cursor:pointer}.primary{background:#222;color:#fff;border-color:#222}.danger{color:var(--danger);border-color:#e5c4c0}.fileLabel input{display:none}.panels{display:grid;grid-template-columns:1fr 1fr;gap:26px;margin-top:22px}.panel h3{font-size:16px;margin:0 0 5px}.muted{color:var(--sub);font-size:13px}.file{display:flex;gap:12px;padding:10px 0;border-bottom:1px solid var(--line)}.file span:first-child{flex:1;min-width:0;overflow-wrap:anywhere}.status{font-size:14px;color:var(--sub);margin-top:10px}.ok{color:#2b7a3d}.finish{padding-top:26px;display:flex;justify-content:space-between;align-items:center;gap:20px}.expired{max-width:680px;margin:80px auto;padding:24px;color:#333}.expired h1{font-size:28px}.testHint{background:#fff7e6;border:1px solid #efcf8c;padding:11px 13px;border-radius:7px;font-size:14px;margin-top:14px}@media(max-width:760px){.wrap{padding:28px 18px 54px}.grid,.panels{grid-template-columns:1fr}.top,.finish{flex-direction:column}.qr{width:200px;height:200px}.btn,.fileLabel{width:100%}}
</style></head><body><main class="wrap">
<div class="top"><div><h1>ファイル転送</h1><p class="lead">{{.DeviceName}} とスマートフォンの間でファイルを送受信します。</p></div>{{if .TestMode}}<div class="badge">VMテストモード</div>{{end}}</div>
<div class="notice">しばらく操作がない場合は自動で終了します。転送が終わったら、画面下の「ファイル転送を終了」を押してください。</div><div id="idleWarn" class="idleWarn">まもなく自動終了します。必要な操作がある場合は続けてください。</div>
{{if .TestMode}}<div class="testHint">テストモードではWi‑Fi Directを使用せず、このWindows内の localhost だけで動作します。</div>{{end}}
<section class="section"><div class="sectionHead"><div class="num">01</div><div><h2>スマホをWi‑Fiに接続</h2><p>{{if .TestMode}}テストモードではこの手順は不要です。{{else}}スマートフォンのカメラでQRコードを読み取ります。{{end}}</p></div></div>{{if .WiFiQR}}<div class="grid"><div><img class="qr" src="/qr.svg?text={{urlquery .WiFiQR}}" alt="Wi-Fi接続用QRコード"></div><div><div class="label">Wi‑Fi名</div><div class="value">{{.WiFiSSID}}</div><div style="height:16px"></div><div class="label">パスワード</div><div class="value mono">{{.WiFiPassword}}</div><div class="muted" style="margin-top:12px">「インターネットなし」と表示されても正常です。</div></div></div>{{else}}<div class="muted">Wi‑Fi接続は使用しません。</div>{{end}}</section>
<section class="section"><div class="sectionHead"><div class="num">02</div><div><h2>転送ページを開く</h2><p>{{if .TestMode}}スマホ側を模擬したページは自動で別タブに開きます。{{else}}Wi‑Fi接続後、次のQRコードを読み取ります。{{end}}</p></div></div>{{range $i,$u := .URLs}}{{if eq $i 0}}<div class="grid"><div><img class="qr" src="/qr.svg?text={{urlquery $u.URL}}" alt="転送ページ用QRコード"></div><div><div class="label">転送ページ</div><div class="url">{{$u.URL}}</div><details class="details"><summary>接続情報を表示</summary><div class="muted" style="margin-top:8px">{{$u.Interface}} / {{$u.IP}}</div></details></div></div>{{end}}{{else}}<div class="muted">転送用ネットワークを確認できませんでした。</div>{{end}}</section>
<section class="section"><div class="sectionHead"><div class="num">03</div><div><h2>ファイルを送受信</h2><p>スマホから送る場合はスマホ側のページを、PCから渡す場合は下のボタンを使います。</p></div></div><div class="actions"><label class="fileLabel primary">スマホに渡すファイルを選ぶ<input id="sharePick" type="file" multiple></label><button class="btn" onclick="openFolder('send')">共有フォルダーを開く</button><button class="btn" onclick="openFolder('receive')">受信フォルダーを開く</button></div><div id="shareStatus" class="status"></div><div class="panels"><div class="panel"><h3>スマホに渡すファイル</h3><div class="muted">スマホ側に表示されます。</div><div id="sendList"></div><button class="btn danger" onclick="clearSide('send')" style="margin-top:12px">共有をすべて解除</button></div><div class="panel"><h3>スマホから受け取ったファイル</h3><div class="muted">スマートフォンから送られたファイルです。</div><div id="recvList"></div><button class="btn danger" onclick="clearSide('receive')" style="margin-top:12px">受信ファイルをすべて削除</button></div></div></section>
<div class="finish"><div><strong>ファイル転送が終わったら</strong><div class="muted" style="margin-top:4px">終了すると転送用Wi‑Fiと今回のセッションが無効になります。</div></div><button class="btn danger" onclick="stopApp()">ファイル転送を終了</button></div>
</main><script>
const admin='/admin/{{.AdminToken}}';let allowClose=false;window.addEventListener('beforeunload',e=>{if(!allowClose){e.preventDefault();e.returnValue=''}});
function fmt(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';if(n<1073741824)return(n/1048576).toFixed(1)+' MB';return(n/1073741824).toFixed(2)+' GB'}
document.getElementById('sharePick').addEventListener('change',async e=>{const st=document.getElementById('shareStatus');for(const f of e.target.files){st.textContent='準備中: '+f.name;await rawUpload(f)}st.textContent='スマホに渡すファイルを用意しました。';st.className='status ok';e.target.value='';loadStatus()});
function rawUpload(f){return new Promise(res=>{const x=new XMLHttpRequest();x.open('POST',admin+'/upload?name='+encodeURIComponent(f.name));x.onload=()=>res();x.onerror=()=>res();x.send(f)})}
async function openFolder(which){await fetch(admin+'/open?which='+which,{method:'POST'})}
async function clearSide(which){if(!confirm(which==='send'?'共有ファイルをすべて解除しますか？':'受信ファイルをすべて削除しますか？'))return;await fetch(admin+'/clear-'+which,{method:'POST'});loadStatus()}
async function loadStatus(){try{const r=await fetch(admin+'/api/status',{cache:'no-store'});if(!r.ok)throw 0;const s=await r.json();render('sendList',s.send,'共有中のファイルはありません');render('recvList',s.receive,'まだ受信ファイルはありません');const idle=Number(s.idleRemainingSec||0),absolute=Number(s.absoluteRemainingSec||0),remain=Math.min(idle,absolute),warn=document.getElementById('idleWarn');warn.style.display=remain>0&&remain<=600?'block':'none';if(remain<=0){allowClose=true;document.body.innerHTML='<div class="expired"><h1>ファイル転送を終了しました</h1><p>セッションの利用時間が終了しました。もう一度利用する場合は Local Phone Transfer を起動してください。</p></div>'}}catch(e){}}
function render(id,fs,empty){const el=document.getElementById(id);if(!fs.length){el.innerHTML='<div class="muted" style="padding:10px 0">'+empty+'</div>';return}el.innerHTML='';for(const f of fs){const d=document.createElement('div');d.className='file';const n=document.createElement('span');n.textContent=f.name;const z=document.createElement('span');z.className='muted';z.textContent=fmt(f.size);d.append(n,z);el.appendChild(d)}}
async function stopApp(){if(!confirm('ファイル転送を終了しますか？'))return;allowClose=true;await fetch(admin+'/stop',{method:'POST'});document.body.innerHTML='<div class="expired"><h1>ファイル転送を終了しました</h1><p>この画面は閉じて大丈夫です。</p></div>'}
loadStatus();setInterval(loadStatus,5000);
</script></body></html>`))
