package main

import "html/template"

var phoneTemplate = template.Must(template.New("phone").Parse(`<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light"><title>スマホからファイル転送</title>
<style>
:root{--bg:#f3f4f6;--panel:#ffffff;--text:#111827;--sub:#4b5563;--line:#d1d5db;--accent:#1d4ed8;--accent2:#dbeafe;--ok:#166534;--warn:#92400e}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.wrap{max-width:760px;margin:0 auto;padding:18px 14px 56px}.banner{background:#0f172a;color:#fff;border-radius:18px;padding:18px 18px 14px}.banner h1{font-size:28px;margin:0 0 6px}.banner p{margin:0;color:#dbe4f0}.notice{margin-top:12px;background:#fffbeb;border:1px solid #fcd34d;color:var(--warn);padding:12px 14px;border-radius:14px;font-size:14px}.section{background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:18px;margin-top:16px;box-shadow:0 1px 2px rgba(0,0,0,.04)}.step{display:flex;align-items:flex-start;gap:12px;margin-bottom:12px}.stepNo{width:34px;height:34px;border-radius:999px;background:#111827;color:#fff;display:grid;place-items:center;font-weight:800;flex:0 0 34px}.stepTitle{font-size:22px;font-weight:800;line-height:1.2}.stepSub{color:var(--sub);font-size:14px;margin-top:4px}.bigAction,.fileLabel{display:block;width:100%;border:0;border-radius:14px;padding:16px 18px;font-size:18px;font-weight:800;text-align:center;cursor:pointer}.bigAction{background:var(--accent2);color:#1e3a8a;border:2px solid #93c5fd}.primary{background:var(--accent);color:#fff;border:0}.fileLabel input{display:none}.row{padding:12px 0;border-top:1px solid var(--line);display:flex;gap:10px;align-items:center}.row:first-child{border-top:0}.name{flex:1;min-width:0;overflow-wrap:anywhere}.size{color:var(--sub);font-size:13px}.download{white-space:nowrap;text-decoration:none;background:#111827;color:#fff;padding:10px 14px;border-radius:10px;font-weight:700}.progressBox{display:none;margin-top:14px}.bar{height:10px;background:#e5e7eb;border-radius:999px;overflow:hidden}.bar>div{height:100%;background:#2563eb;width:0}.status{font-size:15px;margin-top:8px;color:var(--sub)}.ok{color:var(--ok);font-weight:700}.empty{color:var(--sub);padding:10px 0}.hintList{margin:12px 0 0;padding-left:18px;color:var(--sub)}.pill{display:inline-block;background:#eef2ff;color:#3730a3;border-radius:999px;padding:5px 10px;font-size:12px;font-weight:700}.split{display:grid;grid-template-columns:1fr;gap:16px}.topLabel{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px}.subcard{background:#f9fafb;border:1px solid var(--line);border-radius:14px;padding:14px}.foot{text-align:center;color:var(--sub);font-size:12px;margin-top:22px}@media(min-width:700px){.split{grid-template-columns:1fr 1fr}}
</style></head><body><div class="wrap">
<div class="banner"><h1>スマホからファイル転送</h1><p>{{.DeviceName}} にファイルを送ったり、{{.DeviceName}} からファイルを受け取ったりできます。</p></div>
<div class="notice">この画面は閉じずにそのまま使ってください。Wi‑Fiに「インターネットなし」と表示されても正常です。</div>
<div class="split">
<div class="section"><div class="step"><div class="stepNo">1</div><div><div class="stepTitle">スマホ → PC に送る</div><div class="stepSub">レポート、PDF、写真、ZIPなどを{{.DeviceName}}へ送ります。</div></div></div><div class="subcard"><div class="topLabel"><strong>送信するファイルを選ぶ</strong><span class="pill">1ファイル最大 {{.MaxMB}} MB</span></div><label class="fileLabel primary">ファイルを選ぶ<input id="pick" type="file" multiple></label><div id="progress" class="progressBox"><div id="pname" class="status"></div><div class="bar"><div id="pbar"></div></div><div id="ptext" class="status"></div></div><div id="result" class="status"></div><ul class="hintList"><li>複数ファイルも順番に送れます。</li><li>送信が終わるまでこのページを閉じないでください。</li></ul></div></div>
<div class="section"><div class="step"><div class="stepNo">2</div><div><div class="stepTitle">PC → スマホ を受け取る</div><div class="stepSub">PC側で用意されたファイルがここに表示されます。</div></div></div><div class="subcard"><div class="topLabel"><strong>受け取れるファイル一覧</strong><button class="bigAction" onclick="loadFiles()" style="width:auto;padding:10px 14px;font-size:14px">一覧を更新</button></div><div id="files"><div class="empty">確認中...</div></div><ul class="hintList"><li>「受け取る」を押すとダウンロードされます。</li><li>表示されない場合は少し待ってから更新してください。</li></ul></div></div>
</div>
<div class="foot">接続先: {{.DeviceName}} ／ セッション終了後はこのページを再利用できません。</div></div>
<script>
const base='/s/{{.Token}}';const pick=document.getElementById('pick');
function fmt(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';if(n<1073741824)return(n/1048576).toFixed(1)+' MB';return(n/1073741824).toFixed(2)+' GB'}
pick.addEventListener('change',async()=>{for(const f of pick.files){await upload(f)}pick.value='';loadFiles()});
function upload(file){return new Promise((resolve)=>{const xhr=new XMLHttpRequest();const box=document.getElementById('progress'),bar=document.getElementById('pbar'),txt=document.getElementById('ptext'),name=document.getElementById('pname'),res=document.getElementById('result');box.style.display='block';name.textContent='送信中: '+file.name;res.textContent='';bar.style.width='0%';txt.textContent='準備中...';xhr.upload.onprogress=e=>{if(e.lengthComputable){const p=Math.round(e.loaded/e.total*100);bar.style.width=p+'%';txt.textContent=p+'%  ('+fmt(e.loaded)+' / '+fmt(e.total)+')'}};xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300){res.textContent='送信完了: '+file.name;res.className='status ok'}else{res.textContent='送信できませんでした: '+xhr.responseText;res.className='status'}resolve()};xhr.onerror=()=>{res.textContent='通信エラーが発生しました';res.className='status';resolve()};xhr.open('POST',base+'/upload?name='+encodeURIComponent(file.name));xhr.setRequestHeader('Content-Type','application/octet-stream');xhr.send(file)})}
async function loadFiles(){const box=document.getElementById('files');try{const r=await fetch(base+'/api/files',{cache:'no-store'});const fs=await r.json();if(!fs.length){box.innerHTML='<div class="empty">今は受け取れるファイルがありません。</div>';return}box.innerHTML='';for(const f of fs){const d=document.createElement('div');d.className='row';const n=document.createElement('div');n.className='name';n.innerHTML='<strong></strong><div class="size"></div>';n.querySelector('strong').textContent=f.name;n.querySelector('.size').textContent=fmt(f.size);const a=document.createElement('a');a.className='download';a.textContent='受け取る';a.href=base+'/download/'+encodeURIComponent(f.id);d.append(n,a);box.appendChild(d)}}catch(e){box.innerHTML='<div class="empty">PCとの接続を確認してください。</div>'}}
loadFiles();setInterval(loadFiles,5000);
</script></body></html>`))
